### ISSUE TITLE
Tapir fails with random number generators (Tasks again)

### ISSUE THREAD

**Issue by Red-Portal** [compintell/Tapir.jl#182]
The following example fails in both with and without `safe_mode` turned on:

```julia
using DifferentiationInterface, Tapir

function main()
    rng = Random.default_rng()
    f(x) = sum(rand(rng)*x)
    gradient(f, AutoTapir(), ones(10))
end
```

I get the following:
```julia
julia> main()
[ Info: Compiling rule for Tuple{var"#f#2"{TaskLocalRNG}, Vector{Float64}} in safe mode. Disable for best performance.
ERROR: StackOverflowError:
```

Turning `safe_mode` off results in segfault.

**Comment by willtebbutt** [comment]
Two things:
1. I'm really glad that safe mode prevented the segfault, and
2. somewhere in this code we encounter a `Task`. Currently Tapir.jl doesn't handle tasks well because they're self-referential data structures (or, at least, there's something self-referential in them). I really need to fix this.

**Comment by willtebbutt** [comment]
> To clarify, @willtebbutt, does this imply any function that internally involves task switching needs a hand-written rule?

I don't believe so -- it (should) just mean that I need to do something special for tangent generation for tasks. Once that's done it, should all work fine.
